# vim: foldmethod=marker:

# Unite {{{
[[plugins]]
repo = 'Shougo/unite.vim'
depends = [
  'neomru.vim',
  'unite-help',
  'unite-outline',
  'unite-rails',
  'vim-unite-giti',
  'unite-ghq',
  'vim-gista-unite',
  'unite-cmdmatch'
]

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'basyura/unite-rails'

[[plugins]]
repo = 'Shougo/unite-help'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'lambdalisue/vim-gista-unite'
on_source = 'lambdalisue/vim-gista'

[[plugins]]
repo = 'majkinetor/unite-cmdmatch'
on_map = '<Plug>'
# }}}

# Web {{{
[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_path = '.md'
on_map = '<Plug>'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/TweetVim'
depends = [
  'open-browser.vim',
  'twibill.vim',
  'webapi-vim',
  'unite-outline',
  'bitly.vim',
  'unite.vim',
  'favstar-vim'
]
on_cmd = 'TweetVimHomeTimeline'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'mattn/favstar-vim'
# }}}

# Syntax {{{
[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = [
  'vim-quickrun',
  'vimproc.vim',
  'shabadou.vim',
  'vim-hier',
  'quickfixstatus'
]
on_cmd = [
  'WatchdogsRun',
  'WatchdogsRunSilent',
  'WatchdogsRunSweep'
]

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'othree/html5.vim'
# on_ft = 'html'
on_path = '.html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
# on_ft = 'css'
on_path = '.css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
# on_ft = 'javascript'
on_path = '.js'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
# on_ft = 'dockerfile'
on_path = 'Dockerfile'

[[plugins]]
repo = 'slim-template/vim-slim'
# on_ft = 'slim'
on_path = '.slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
# on_ft = 'coffee'
on_path = '.coffee'
# }}}

# Completion {{{
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_i = 1
on_ft = 'snippet'
on_map = '<Plug>'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mattn/emmet-vim'
# on_ft?
on_path = [
  '.html',
  '.css',
  '.scss',
  '.slim',
  '.eruby',
  '.markdown'
]
# }}}

# Others {{{
[[plugins]]
repo = 'cohama/vim-smartinput-endwise'
depends = 'vim-smartinput'
on_i = 1
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'fatih/vim-go'
# on_ft = 'go'
on_path = '.go'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1
# }}}
