# vim: foldmethod=marker:

# Syntax {{{
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = 'yaml'
# }}}

# Others {{{
[[plugins]]
repo = 'Shougo/vimfiler'
depends = ['unite.vim', 'vim-devicons']
on_map = [['n', '<Plug>']]
on_path = '.*'
hook_add = ''' "{{{
  let g:vimfiler_as_default_explorer = 1
  autocmd FileType vimfiler 
        \ nnoremap <buffer><silent>/ 
        \ :<C-u>Unite file -default-action=vimfiler<CR>
  autocmd FileType vimfiler setlocal statusline=VimFiler
  autocmd VimEnter * nested if @% == '' && s:bufByte() == 0 | VimFiler | endif
  function! s:bufByte()
    return line2byte(line('$') + 1) == -1 ? 0 : -1
  endfunction
" }}} '''
hook_source = ''' "{{{
  call vimfiler#custom#profile('default', 'context', { 'auto_cd' : 1 })
" }}} '''

[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'md'
on_map = '<Plug>'
hook_add = ''' "{{{
  nnoremap [Previm] <Nop>
  nmap <Space>pv [Previm]

  nnoremap <silent> [Previm] :<C-u>PrevimOpen<CR>
" }}} '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-smart-search)'
hook_add = ''' " {{{
  let g:netrw_nogx = 1
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
" }}} '''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>(caw:hatpos:toggle)'
hook_add = ''' " {{{
  filetype plugin on
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
" }}} '''
# }}}
