#!/usr/bin/env perl

$bibtex        = 'pbibtex';
$clean_ext     = "lol mtc maf";
$dvi_previewer ='pxdvi';
$dvipdf        = 'dvipdfmx %O -o %D %S';
$dvips         = 'pdvips';
$latex         = 'platex -halt-on-error -file-line-error -src-specials';
$latex_silent  = 'platex -halt-on-error -file-line-error -src-specials -interaction=batchmode';
$pdf_mode      = 3;
$sleep_time    = 1;
@default_files = 'main.tex';
