[[snippets]]
  description = "Update known_hosts file"
  command = "fillin \"ssh-keygen -R {{ssh:host}} && ssh-keyscan -Hp {{ssh:port}} {{ssh:host}} >>~/.ssh/known_hosts\""
  tag = ["ssh"]
  output = ""

[[snippets]]
  description = "Remove dangling images"
  command = "docker image prune --filter dangling=true"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Remove volumes"
  command = "docker volume prune"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Show git alias"
  command = "git config --get-regexp alias | sed 's/alias\\.\\([^ ]*\\) \\(.*\\)/\\1\\t -> \\2/'"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "Create git repository"
  command = "fillin 'mkdir `ghq root`/{{git:host}}/$USER/{{git:dir}} && git -C $_ init'"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "Measure the amount of time elapsed"
  command = "bash -c 'time read' 2>&1 | awk 'NR==2{print $2}'"
  tag = ["stopwatch"]
  output = ""

[[snippets]]
  description = "Flush DNS cache"
  command = "sudo pdnsd-ctl empty-cache"
  tag = ["dns", "cache"]
  output = ""

[[snippets]]
  description = "Remove cache of pacman"
  command = "sudo pacman -Sc --noconfirm"
  tag = ["archlinux", "pacman"]
  output = ""

[[snippets]]
  description = "Analyze system boot-up performance"
  command = "sudo systemd-analyze"
  output = ""

[[snippets]]
  description = "Show true color"
  command = "fillin 'hex={{color:hex}}; printf \"$hex: \\e[48;2;%d;%d;%dm     \\e[0m\\n\" \"0x${hex:1:2}\" \"0x${hex:3:2}\" \"0x${hex:5:2}\"'"
  tag = ["color"]
  output = ""
