#!/bin/zsh

if ! type chromium >/dev/null 2>&1; then
  notify-send Aggregator 'Command not found: chromium'
  exit 1
fi

if ! type feedlish >/dev/null 2>&1; then
  notify-send Aggregator 'Command not found: feedlish'
  exit 1
fi

private -a aggregators
aggregators=(feedly reddit hatena)

private aggregator=`printf '%s\n' $aggregators | dmenu -p 'Aggregator' ${=DMENU}`

if [[ $aggregator = feedly ]]; then
  termite -e feedlish
elif [[ $aggregator = reddit ]]; then
  chromium --app="https://www.reddit.com/"
elif [[ $aggregator = hatena ]]; then
  chromium --app="http://b.hatena.ne.jp/" --incognito
fi
