#!/bin/zsh

if ! type netctl-auto >/dev/null 2>&1; then
  notify-send NetworkSwitcher 'command not found: netctl-auto'
  exit 1
fi

profile=`
  netctl-auto list | \
    grep -v '*' | \
    sed 's/ //g' | \
    dmenu -p 'Network' ${=DMENU}
`

sudo netctl-auto switch-to $profile
