#!/bin/zsh

power=( halt reboot lock logout )

input=`<<< ${(F)power} | dmenu -p 'Power' ${=DMENU}`

case $input in
  halt) halt -p ;;
  reboot) reboot ;;
  lock)
    pidfile=/tmp/unclutter.pid
    if [[ ! -f $pidfile ]]; then
      light-locker-command -l
    else
      killall unclutter
      rm "$pidfile"
      light-locker-command -l
      unclutter -idle 1 -root -grab &
      echo $! > "$pidfile"
    fi
    ;;
  logout) xdotool key "super+shift+q" ;;
  *) ;;
esac
