#!/bin/zsh

if ! type light-locker-command >/dev/null 2>&1; then
  notify-send PowerManager 'Command not found: light-locker-command'
  exit 1
fi

if ! type unclutter >/dev/null 2>&1; then
  notify-send PowerManager 'Command not found: unclutter'
  exit 1
fi

power=( halt reboot lock )

input=`<<< ${(F)power} | dmenu -p 'Power' ${=DMENU}`

case $input in
  halt) halt -p ;;
  reboot) reboot ;;
  lock)
    pidfile=/tmp/unclutter.pid
    if [[ ! -f $pidfile ]]; then
      light-locker-command -l
    else
      killall unclutter
      rm "$pidfile"
      light-locker-command -l
      unclutter -idle 1 -root -grab &
      echo $! > "$pidfile"
    fi
    ;;
  *) ;;
esac
