# vim: foldmethod=marker:

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin = 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    linux = 'make'
    unix = 'gmake'

# Git {{{
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/vim-gista'
if = 'has("python3")'
# }}}

# operator {{{
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
# }}}

# textobj {{{
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
# }}}

# Others {{{
[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
depends = 'unite.vim'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = 'has("python3")'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'tyru/eskk.vim'
