#!/bin/zsh

check-version() { [[ `tmux -V` =~ $1 ]] && return 0 || return 1; }

if check-version '^.+2\.[123]$'; then
  tmux bind -n WheelUpPane if -Ft= '#{mouse_any_flag}' 'send -M' \
    "if -Ft= '#{pane_in_mode}' 'send -M' 'copy-mode -e'"
  if [[ $1 = on ]]; then
    tmux set-option -g mouse on
    tmux display 'Mouse: ON'
  elif [[ $1 = off ]]; then
    tmux set-option -g mouse off
    tmux display 'Mouse: OFF'
  fi
elif check-version '^.+(2\.0|1\.9a?)$'; then
  ## versions earlier than 2.1
  if [[ $1 = on ]]; then
    tmux set-window-option -g mode-mouse on
    tmux set-option -g mouse-select-pane on
    tmux set-option -g mouse-resize-pane on
    tmux set-option -g mouse-select-window on
    tmux display 'Mouse: ON'
  elif [[ $1 = off ]]; then
    tmux set-window-option -g mode-mouse off
    tmux set-option -g mouse-select-pane off
    tmux set-option -g mouse-resize-pane off
    tmux set-option -g mouse-select-window off
    tmux display 'Mouse: OFF'
  fi
fi
