#!/bin/zsh

if ! type xbacklight >/dev/null 2>&1; then
  notify-send Brightness 'command not found: xbacklight'
  exit 1
fi

private MIN=5.5 MAX=50
private DEFAULT=2 AMOUNT=5
private current=`xbacklight -get`

case $1 in
  + )
    (( $current < $MAX )) && xbacklight + $AMOUNT
    ;;
  - )
    (( $current > $MIN )) && xbacklight - $AMOUNT
    ;;
  '' )
    xbacklight = $DEFAULT
    ;;
esac
