#!/bin/zsh

if xmonad --recompile >/dev/null 2>&1; then
  xmonad --restart >/dev/null 2>&1
  notify-send "xmonad" "Compiled and Restarted"
else
  notify-send "xmonad" "Error detected while loading configuration file"
  exit 1
fi
