#!/bin/zsh

if ! type ffmpeg >/dev/null 2>&1; then
  notify-send Screencast 'command not found: ffmpeg'
  exit 1
fi

screencast-box() {
  typeset size display file
  size=$1
  display="$2"
  file=~/Videos/Screencasts/$(date +'%y-%m-%d_%I%M%S').mp4
  ffmpeg -f x11grab -s "$size" -i "$display" -f alsa -i default -c:v libx264 -c:a aac -qp 0 "$file"
  notify-send 'Recorded screen' "Saved to $file"
}

screencast-full() {
  typeset size
  size=`xwininfo -root | awk '/-geo/{print $2}' | grep -Eo '^[0-9]*x[0-9]*'`
  screencast-box "$size" "$DISPLAY"
}

screencast-select() {
  eval $(slop -b 1 -c 0,0,255,1)
  screencast-box "$W"x"$H" :0.0+$X,$Y
}

if ! killall ffmpeg; then
  if [[ $1 = --select ]]; then
    if [[ -f /tmp/unclutter.pid ]]; then
      mouse
      screencast-select
      mouse
    else
      screencast-select
    fi
  else
    screencast-full
  fi
fi
