#!/bin/zsh

take-screenshot() {
  file=$HOME/Pictures/Screenshots/$(date +'%y-%m-%d_%I%M%S').png
  if [[ $1 = --select ]]; then
    maim -s -b 1 -c 0,0,255,1 "$file"
  else
    maim "$file"
  fi
  if [[ $? != 1 ]]; then
    notify-send 'Take a screenshot' "Saved to $file"
  fi
}

if [[ -f /tmp/unclutter.pid ]]; then
  mouse
  take-screenshot $1
  mouse
else
  take-screenshot $1
fi
