#!/bin/zsh

if ! type light-locker >/dev/null 2>&1; then
  notify-send xmonad 'command not found: light-locker'
  exit 1
fi

if ! type xautolock >/dev/null 2>&1; then
  notify-send xmonad 'command not found: xautolock'
  exit 1
fi

light-locker --lock-on-suspend --late-locking &
xautolock \
  -time 10 \
  -locker 'light-locker-command -l' \
  -notify 30 \
  -notifier "notify-send xautolock 'LOCKING screen in 30 seconds'" &
