#!/bin/zsh

private MIN=5.5 MAX=50
private DEFAULT=2 AMOUNT=5
private current=`xbacklight -get`

case $1 in
  + )
    (( $current < $MAX )) && xbacklight + $AMOUNT
    ;;
  - )
    (( $current > $MIN )) && xbacklight - $AMOUNT
    ;;
  = )
    xbacklight = $DEFAULT
    ;;
esac
