#!/bin/zsh

case $1 in
  toggle )
    # xautomation
    xte 'mousemove 0 0'

    # Unclutter
    pidfile=/tmp/unclutter.pid
    if [[ ! -f $pidfile ]]; then
      unclutter -idle 1 -root -grab &
      echo $! > "$pidfile"
    else
      killall unclutter
      rm "$pidfile"
    fi

    # Others
    if [[ -z $MOUSE ]]; then
      notify-send "xmonad-system" 'not set `$MOUSE`'
      exit 1
    fi
    typeset ID
    ID=`xinput list | grep "$MOUSE" | grep -Eo 'id\=[0-9]*' | grep -Eo '[0-9]*'`
    declare -i STATE
    STATE=`xinput list-props "$ID" | grep 'Device Enabled' | awk '{print $4}'`
    if [[ $STATE = 1 ]]; then
      xinput disable $ID
      notify-send "$MOUSE" "Disabled touchpad"
    else
      xinput enable $ID
      notify-send "$MOUSE" "Enabled Touchpad"
    fi
    ;;
  down )
    xte 'mousermove 0 10'
    ;;
  up )
    xte 'mousermove 0 -10'
    ;;
  left )
    xte 'mousermove -10 0'
    ;;
  right )
    xte 'mousermove 10 0'
    ;;
  click )
    xte 'mouseclick 1'
    ;;
esac
