alias cp 'cp --interactive --verbose'
alias exa 'exa --classify --time-style long-iso --git'
alias feedlish 'envchain ytet5uy4/feedly feedlish'
alias ghi 'envchain ytet5uy4/gh ghi'
alias git hub
alias hub 'envchain ytet5uy4/gh hub'
alias mv 'mv --interactive --verbose'
alias nvim 'nvim -p'
alias rm 'rm --interactive --verbose'
alias ssh 'TERM=xterm-256color command ssh'
