" Declare rc_vim_list and source_rc
let rc_vim_list = [
\   "plugins",
\   "apperance",
\   "base",
\   "colors",
\   "keymap",
\   "local"
\ ]

function! s:source_rc(path)
  execute 'source' fnameescape(expand('~/.vim/rc/' . a:path . '.vim'))
endfunction

" Source settings
" Location: ~/.vim/rc/
for rc_vim in rc_vim_list
  cal s:source_rc(rc_vim)
endfor
