# vim: foldmethod=marker:

# Base {{{
[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'md'
on_map = '<Plug>'
hook_add = ''' "{{{
  nnoremap [Previm] <Nop>
  nmap <Space><C-p> [Previm]

  nnoremap <silent> [Previm] :<C-u>PrevimOpen<CR>
" }}} '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-smart-search)'
hook_add = ''' " {{{
  let g:netrw_nogx = 1
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
" }}} '''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>(caw:hatpos:toggle)'
hook_add = ''' " {{{
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
" }}} '''
# }}}

# Completion {{{
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'
# }}}

# Syntax {{{
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add ='let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'zchee/nvim-go'
build = 'make'
on_ft = 'go'
hook_add = '''
augroup nvim-go
  autocmd!
  autocmd FileType go nnoremap <C-c> :<C-u>Gorun<CR>
  autocmd FileType go nnoremap g<C-c> :<C-u>Gorun<space>
  autocmd FileType go nnoremap = :<C-u>Gofmt<CR>:<C-u>Neomake<CR>
augroup END
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'tf'
# }}}
