# Base {{{
[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
on_map = '<Plug>'
hook_add = ''' "{{{
augroup previm
  autocmd!
  autocmd FileType markdown nnoremap [Previm] <Nop>
  autocmd FileType markdown nmap <Space><C-p> [Previm]
  autocmd FileType markdown nnoremap <silent> [Previm] :<C-u>PrevimOpen<CR>
augroup END
" }}} '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-smart-search)'
hook_add = ''' " {{{
let g:netrw_nogx = 1
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
" }}} '''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>(caw:hatpos:toggle)'
hook_add = ''' " {{{
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
" }}} '''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_if = 'has("python3")'
hook_add = 'let g:EditorConfig_exclude_patterns = ["scp://.*"]'

[[plugins]]
repo = 'fatih/vim-hclfmt'
on_ft = 'hcl'
hook_add = '''
let g:hcl_fmt_autosave = 0
let g:tf_fmt_autosave = 0
let g:nomad_fmt_autosave = 0
augroup hclfmt
  autocmd!
  autocmd FileType hcl nnoremap = :<C-u>HclFmt<CR>:<C-u>Neomake<CR>
augroup END
'''
# }}}

# Completion {{{
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'
# }}}

# Syntax {{{
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add ='''
augroup vim-json
  autocmd!
  autocmd FileType json let g:vim_json_syntax_conceal = 0
augroup END
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'tf'
hook_add = '''
let g:terraform_fmt_on_save = 1
augroup vim-terraform
  autocmd!
  autocmd FileType terraform nnoremap = :<C-u>TerraformFmt<CR>:<C-u>Neomake<CR>
augroup END
'''

[[plugins]]
repo = 'baskerville/vim-sxhkdrc'
on_ft = 'sxhkdrc'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'
# }}}

# vim: foldmethod=marker:
