# Base {{{
[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
on_map = '<Plug>'
hook_add = ''' "{{{
augroup previm
  autocmd!
  autocmd FileType markdown nnoremap [Previm] <Nop>
  autocmd FileType markdown nmap <Space><C-p> [Previm]
  autocmd FileType markdown nnoremap <silent> [Previm] :<C-u>PrevimOpen<CR>
augroup END
" }}} '''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-smart-search)'
hook_add = ''' " {{{
let g:netrw_nogx = 1
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
" }}} '''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>(caw:hatpos:toggle)'
hook_add = ''' " {{{
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
" }}} '''
# }}}

# Completion {{{
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'zchee/deoplete-docker'
on_ft = 'dockerfile'
# }}}

# Syntax {{{
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add ='''
augroup vim-json
  autocmd!
  autocmd FileType json let g:vim_json_syntax_conceal = 0
augroup END
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'zchee/nvim-go'
build = 'make'
on_ft = 'go'
hook_add = '''
augroup nvim-go
  autocmd!
  autocmd FileType go nmap <C-c> <Plug>(nvim-go-run)
  autocmd FileType go nnoremap g<C-c> :<C-u>Gorun<space>
  autocmd FileType go nnoremap = :<C-u>Gofmt<CR>:<C-u>Neomake<CR>
  autocmd FileType go nnoremap <Space>d :<C-u>DlvDebug<CR>
  autocmd FileType go nnoremap <Space>gd :<C-u>DlvDebug --<space>
  autocmd FileType go nnoremap <Space>b :<C-u>DlvBreakpoint<CR>
  autocmd FileType go nnoremap <Space>c :<C-u>DlvContinue<CR>
  autocmd FileType go nnoremap <Space>n :<C-u>DlvNext<CR>
augroup END
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'tf'
# }}}

# vim: foldmethod=marker:
