[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'let g:dein#types#git#clone_depth = 1'

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['.git']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \   'colorscheme': 'abyss',
      \   'active': {
      \     'left': [['mode', 'paste'],['readonly', 'vcs', 'filename', 'modified']],
      \     'right': [['lineinfo'], ['filetype'], ['fileformat', 'fileencoding', 'syntaxcheck']],
      \   },
      \   'component': {
      \     'lineinfo': '%-2v',
      \   },
      \   'component_expand': {
      \     'syntaxcheck': 'plugin#lightline#syntaxcheck',
      \   },
      \   'component_type': {
      \     'syntaxcheck': 'error',
      \   },
      \   'component_function': {
      \     'vcs': 'plugin#lightline#vcs',
      \     'fileformat': 'plugin#lightline#fileformat',
      \     'filetype': 'plugin#lightline#filetype',
      \     'fileencoding': 'plugin#lightline#fileencoding',
      \     'filename': 'plugin#lightline#filename',
      \   },
      \   'mode_map': {
      \     'n' : 'N',
      \     'i' : 'I',
      \     'R' : 'R',
      \     'v' : 'V',
      \     'V' : 'VL',
      \     "\<C-v>": 'VB',
      \     'c' : 'C',
      \     's' : 'S',
      \     'S' : 'SL',
      \     "\<C-s>": 'SB',
      \     't': 'T',
      \   },
      \   'separator': {
      \     'left': "\ue0b0",
      \     'right': "\ue0b2",
      \   },
      \   'subseparator': {
      \     'left': "\ue0b1",
      \     'right': "\ue0b3",
      \   },
      \ }
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
let g:fzf_command_prefix = 'FZF'
nnoremap <silent> <Space>f :<C-u>FZFFiles<CR>
nnoremap <silent> <Space>w :<C-u>FZFWindows<CR>
command! -bang -nargs=* FZFRg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
nnoremap <silent> <Space>g :<C-u>FZFRg<CR>
autocmd! User FzfStatusLine silent
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = 'let g:EditorConfig_exclude_patterns = ["scp://.*"]'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vimtaku/vim-textobj-sigil'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'fvictorio/vim-textobj-backticks'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_lint_on_text_changed = 0
let g:ale_set_highlights = 0
let g:ale_sign_error = '•'
let g:ale_sign_warning = '•'
highlight ALEErrorSign guifg='#FE0000'
highlight ALEWarningSign guifg='#FE0000'
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

nmap <silent> <Space><C-k> <Plug>(ale_previous_wrap)
nmap <silent> <Space><C-j> <Plug>(ale_next_wrap)

augroup ale_settings
  autocmd!
  autocmd User ALELint call lightline#update()
augroup END
'''
