#!/bin/zsh

if type light-locker; then
  light-locker --lock-on-suspend &
  if type xautolock; then
    xautolock \
      -time 10 \
      -locker 'light-locker-command -l' \
      -notify 30 \
      -notifier "notify-send 'xautolock' 'LOCKING screen in 30 seconds'" &
  else
    notify-send xmonad 'command not found: xautolock'
  fi
else
  notify-send xmonad 'command not found: light-locker'
fi
