#!/bin/zsh

if ! type pamixer >/dev/null 2>&1; then
  notify-send Volume 'command not found: pamixer'
  exit 1
fi

file="/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"

case $1 in
  m )
    pamixer --toggle-mute
    ;;
  + )
    pamixer --increase 1 && paplay $file
    ;;
  - )
    pamixer --decrease 1 && paplay $file
    ;;
esac
