#!/bin/zsh

if ! type lpass; then
  notify-send 'Password Manager' 'Command not found: lpass'
  exit 1
fi

if ! lpass status -q; then
  notify-send 'Password Manager' 'Not logged in lpass'
  exit 1
fi

name=`
  lpass ls | \
    sed -E 's/ \[id: ([0-9]+)\]//' | \
    dmenu -p 'Password Manager' ${=DMENU}
`

if [[ $name ]]; then
  lpass show -- $name | \
    sed -n -E 's/^(Password|Passphrase): //gp' | \
    uniq | \
    xsel -bi

  notify-send 'Password Manager' "Copied password: $name"
fi
