#! /bin/sh

bspwmstatus | xmobar &

bspc monitor -d 1 2 3

bspc config border_width  2
bspc config window_gap   12

bspc config normal_border_color  '#343434'
bspc config active_border_color  '#343434'
bspc config focused_border_color '#1034a6'

bspc rule -a Zathura state=tiled
