#! /bin/sh

bspwmstatus | xmobar &

bspc monitor --reset-desktops 1 2 3

bspc config border_width  2
bspc config window_gap   12

bspc config normal_border_color  '#343434'
bspc config active_border_color  '#343434'
bspc config focused_border_color '#1034a6'

bspc rule --add Zathura state=tiled

source $XDG_CONFIG_HOME/bspwm/bspwmrc.local
