#!/bin/zsh

type pkgfile >/dev/null 2>&1 || return 1

private cmd
private -a pkgs
cmd="$1"
pkgs=(${(f)"$(pkgfile -b -v -- "$cmd" 2>/dev/null)"})
if [[ -n $pkgs ]]; then
  printf '%s may be found in the following packages:\n' "$cmd"
  printf '  %s\n' $pkgs
  return 0
else
  printf 'zsh: command not found: %s\n' "$cmd"
fi

return 127
