#!/bin/zsh

[[ ! -r $PWD ]] && return

private cmd_ls='ls'
private -a opt_ls
opt_ls=('-ACF' '--color=always')

private ls_result
ls_result=$(CLICOLOR_FORCE=1 COLUMNS=$COLUMNS command $cmd_ls ${opt_ls[@]} | sed $'/^\e\[[0-9;]*m$/d')

private ls_lines=$(echo "$ls_result" | wc -l | tr -d ' ')

if [ $ls_lines -gt 10 ]; then
  echo "$ls_result" | head -n 5
  echo '...'
  echo "$ls_result" | tail -n 5
  echo "$(command ls -1 -A | wc -l | tr -d ' ') files exist"
else
  echo "$ls_result"
fi
