#!/bin/zsh

if ! type jq >/dev/null 2>&1; then
  notify-send Video 'command not found: jq'
  exit 1
fi

if ! type mpv >/dev/null 2>&1; then
  notify-send Video 'command not found: mpv'
  exit 1
fi

if ! type youtube-dl >/dev/null 2>&1; then
  notify-send Video 'command not found: youtube-dl'
  exit 1
fi

private file=$XDG_CONFIG_HOME/youtube/playlists.json

if ! [[ -f $file ]]; then
  notify-send 'Video' "config file not found: $file"
  exit 1
fi

private -a playlist
playlist=(`jq -r '.playlists[].title' $file`)

private title=`printf '%s\n' $playlist | dmenu -p 'Video' ${=DMENU}`

private id=`jq -r ".playlists[]|select(.title==\"$title\").id" $file`

if [[ -n $id ]]; then
  notify-send 'Video' 'Downloading playlist...'
  mpv --shuffle ytdl://$id
fi
