#!/bin/zsh

private -A abbreviations
abbreviations=(
  'F'   '| fzf-tmux'
  'G'   '| rg'
  'X'   '| xargs'
  'T'   '| tail'
  'H'   '| head'
  'C'   '| cat'
  'W'   '| wc'
  'L'   '| less'
  'A'   '| awk'
  'S'   '| sed'
  'E'   '2>&1 >/dev/null'
  'N'   '>/dev/null'
)

local MATCH
LBUFFER=${LBUFFER%%(#m)[-_a-zA-Z0-9]#}
LBUFFER+=${abbreviations[$MATCH]:-$MATCH}
zle self-insert
