#!/bin/zsh

private -A abbreviations
abbreviations=(
  'G' '| rg'
  'X' '| xargs'
  'T' '| tail'
  'H' '| head'
  'W' '| wc'
  'L' '| less'
  'A' '| awk'
  'S' '| sed'
)

local MATCH
LBUFFER=${LBUFFER%%(#m)[-_a-zA-Z0-9]#}
LBUFFER+=${abbreviations[$MATCH]:-$MATCH}
zle self-insert
